### PR TITLE
fix: missing remark-lint-list-item-indent in devDependencies

### PR DESCRIPTION
**Pull request by aheissenberger**
### Initial checklist

*   [X ] I read the support docs 
*   [X] I read the contributing guide 
*   [X] I agree to follow the code of conduct 
*   [X] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [X] If applicable, I’ve added docs and tests

### Description of changes

add missing remark-lint-list-item-indent to `devDependencies` in `package.json`

**Error Message:**

```sh
$ pnpm test

> mdast-zone@6.1.0 test /Users/ah/SVN-Checkouts/TST/mdast-zone
> npm run build && npm run format && npm run test-coverage


> mdast-zone@6.1.0 build
> tsc --build --clean && tsc --build && type-coverage

(385 / 385) 100.00%
type-coverage success.

> mdast-zone@6.1.0 format
> remark . -qfo && prettier . -w --log-level warn && xo --fix

readme.md
 error Cannot process file
  [cause]:
    Error: Cannot find module `remark-lint-list-item-indent`
```

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Welcome @aheissenberger! 👋 

Taking a step back.
1. I notice you are using `pnpm`, that depedency manager has different resolution rules than `npm` or `yarn` that may be the source of the issue
2. If you do believe this is an issue with a unified project and not `pnpm`, that dependency is a transitive of `remark-preset-wooorm`
   1. the version of the preset here is a major version behind, consider updating `remark-cli`, `remark-gfm`, and `remark-preset-wooorm` to the latest major version instead
   2. If the issue still presists after upgrading the major versions, open a PR to https://www.npmjs.com/package/remark-preset-wooorm

**Comment by wooorm** [comment]
I’ve updated the deps in https://github.com/syntax-tree/mdast-zone/commit/ddf0530744c2d2e7bac00ca34b72618200180a11. But yes: we use `npm` to maintain our things. If you’re checking out our projects, I recommend using that.

**Comment by aheissenberger** [comment]
> But yes: we use `npm` to maintain our things. If you’re checking out our projects, I recommend using that.

If `npm` is a requirement please add property "packageManager" to package.json.

Thanks for the quick response and your projects!
Andreas

**Comment by wooorm** [comment]
Not sure that does what you want: https://github.com/nodejs/node/issues/51888.

That field is also very [experimental](https://nodejs.org/api/packages.html#packagemanager).

And wasn’t corepack going away?

**Pull request closed without merging**
